version: '3.3'
services:
  mysql:
    hostname: mysql-hostname
    image: mysql
    container_name: liquibase-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      -  internal_network

  liquibase:
    image: parvin02/burhan:v1
    #    build: .
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_CONNECTION_IP: "mysql-hostname"
    networks:
      - internal_network
    depends_on:
      - mysql

networks:
  internal_network:

volumes:
  db_data: